export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROGRESS = "GET_PROGRESS";
export const PROGRESS_LOADING = "PROGRESS_LOADING";
export const PROGRESS_NOT_FOUND = "PROGRESS_NOT_FOUND";
export const CLEAR_CURRENT_PROGRESS = "CLEAR_CURRENT_PROGRESS";
